### ISSUE TITLE
[Q&A] regarding ignited sync

### ISSUE THREAD

**Issue by bachig26** [Lit-Development/Ignited#11]
**Q1**
- currently while using the sync, the permission request to allow the app to sync with cloud acts as the delta is being used.
will it be changed in future as ignited to have it's own? 
i don't much about this, maybe it still uses the delta backend api or something...I'm not quite knowledgeable on this but just happen remember and noticed again today while switching between GDrive and Dropbox.

**Q2**
- will there be more services support be added like Nextcloud, OneDrive?

**Comment by LitRitt** [comment]
Q1: Yes, it will remain this way to maintain syncing compatibility with Delta

Q2: There's no plans, but it shouldn't be too challenging to accomplish
