### ISSUE TITLE
[BUG] accent color issue around the button

### ISSUE THREAD

**Issue by bachig26** [Lit-Development/Ignited#12]
As you can see in the clip below, the accent color for `AUTO LOAD SAVE STATES` reflects the original color while toggling the button.

i think this may be a bug and i wasn't able to reproduce in other buttons and only able reproduce every time when I toggle this one button.

#### Clip

https://user-images.githubusercontent.com/96393348/230802827-f86d1d69-611f-4bd1-bb00-4ea17bb3fada.mov

**Comment by LitRitt** [comment]
Not able to replicate, might be an old issue that was already addressed
