### ISSUE TITLE
[BUG] Homepage Switcher not working

### ISSUE THREAD

**Issue by bachig26** [Lit-Development/Ignited#13]
As you can see the bottom of the app for the page switcher, it should work as similar to the Apple Homepage switcher by holding and hovering over the pages to switch between them but only the indicator icon is showing as the page been switched but the actual page hasn't been updated.

please have a look into this issue.

#### Clip

https://user-images.githubusercontent.com/96393348/230803427-23dbce8c-9d5a-4fe6-a546-e763c4e23109.mov

**Comment by LitRitt** [comment]
There's no implementation for that, and it doesn't quite work with how data sources are handled. I recently disabled the ability to swipe like that so it's not confusing. No plans to implement this behavior
