### ISSUE TITLE
[Improvement] toast toggle for ignited sync

### ISSUE THREAD

**Issue by bachig26** [Lit-Development/Ignited#14]
A toggle option for the ignited sync toast would nice, this can avoid the frequent toasts that appears every time and be in a silent sync mode,

#### Screenshot

![syctoast](https://user-images.githubusercontent.com/96393348/231596630-db104783-384a-4fac-b563-947111582775.jpg)
![toastissu](https://user-images.githubusercontent.com/96393348/231596635-76542966-a829-4f49-a503-b95b2540a803.jpg)

**Comment by LitRitt** [comment]
As Ignited's sync isn't a passive/silent process, meaning it can be interrupted and cause failures, I think it's best to keep the sync notification at all times
