### ISSUE TITLE
[Feature] Library

### ISSUE THREAD

**Issue by bachig26** [Lit-Development/Ignited#16]
### Feature Idea

A `Library` page similar to which the NES, GBA, etc. pages created when installing their respective games.

In this Library page, we can have the sections like favorited games from various console options in one place, also sections like the most played games, recently played games. 

Furthermore, it would be also nice to have an pinned option in their respective console view/page where the user can pin a game and access them without having to scrolling through the list

In a way, this will improve the user experience to get access to their particular games when the user having a large game library in Ignited more easily and have more basic information on their gameplay with Ignited.

**Comment by LitRitt** [comment]
Not sold on having a whole other page for them, but I like the idea of being able to favorite games and they appear at the top of their page with some icon.

**Comment by BAS27-BKK** [comment]
> ### Feature Idea
> A `Library` page similar to which the NES, GBA, etc. pages created when installing their respective games.
> 
> In this Library page, we can have the sections like favorited games from various console options in one place, also sections like the most played games, recently played games.
> 
> Furthermore, it would be also nice to have an pinned option in their respective console view/page where the user can pin a game and access them without having to scrolling through the list
> 
> In a way, this will improve the user experience to get access to their particular games when the user having a large game library in Ignited more easily and have more basic information on their gameplay with Ignited.
