### ISSUE TITLE
Imported dsinand.bin by accident, can't be deleted without crashing

### ISSUE THREAD

**Issue by NewsGuyTor** [Lit-Development/Ignited#17]
I figured that it should work to just add the firmwares using the + button. However, instead it added is as a Genesis rom that can't be deleted, as when I long press it and try to delete it Ignited crashes.

**Comment by LitRitt** [comment]
You need to disable game previews

**Comment by 7ank0v1c** [comment]
Yeah game previews try’s to load the nand as a genesis rom. Because it’s doesn’t know what to do with it it just crashes. Disable the preview and delete it. Then enable after again and job done 👏 😊

**Comment by NewsGuyTor** [comment]
Yeah, thanks, that works, but I think it should import them as firmwares instead of crashing.

**Comment by 7ank0v1c** [comment]
The way the emulator currently imports Roms assumes all '.bin' files are genesis Roms. The easiest solution might possibly be to have a selection screen pop up when importing files with extensions with multiple uses, so that you can then direct the file correctly. Provenance does this well actually
