### ISSUE TITLE
[Feature] Choose between using RTC or a stand-alone in-app clock.

### ISSUE THREAD

**Issue by LCRich2001** [Lit-Development/Ignited#22]
I hope this makes sense. Basically I want to be able to manipulate the time just within the emulator. The time being tied to the phone's RTC is neat, but is also annoying. Changing my phone's date/time fucks with notifications, internet, and a whole host of other problems. If it's possible, I'd prefer to just be able manipulate the time within the emulator.

Also, not sure if this is technically a bug, but time manipulation breaks auto save (kinda). Basically, if you time manipulate into the future, the auto save will trigger at some point and promptly create a save state like normal. However, if/when you revert back to real-time or any time prior to the date/time marked on the auto-save state, the auto save refuses to overwrite the save state (because it's dated for the future).

Would there be any way to fix this? My guess is that a fix for this would be too complicated. However, I think adding an independent clock feature (like I suggested above) would actually be a proper workaround. The emulator's auto-save states would function purely on the phone's RTC (like it does now), but if there was a changeable, in-emulator clock that the games would recognize, then there would be no need to change the phone's RTC; and therefore it would cause no issues with auto-save or other phone related operations.

Is any of this possible for Ignited? Or should I make this request over at the Delta repo?

**Comment by LitRitt** [comment]
Possible maybe? RTC is pretty deeply rooted in the emulator core code, the DeltaCores don't even currently manipulate or even touch it. Seems to get it's time from built in C api calls or something.

I have no plans to support this or anything related to time manipulation.
