### ISSUE TITLE
Add FDS support, cheat codes for genesis, and ABCD:EF cheat code support for nes

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [Lit-Development/Ignited#24]
The nes is good and all, but there are some games that look better on the famicom disk system, and I’d like you to add support for it. Swapping disks and adding the bios would also be a nice feature. The sega genesis is the only compatible console that doesn’t support cheat codes, and I was thinking if you could at support for them, both game genie and action replay. Last but not least, some nes cheat codes aren’t compatible with the game genie, so I was thinking if you could add cheat codes that support the ABCD:EF format, for example in Puyo puyo for the famicom, always having lime green Puyos is this code: 00F0:E0, 00F1:3C

**Comment by LitRitt** [comment]
The only thing in your list I would consider at some point is adding cheat support to Genesis, since it's already a supported system. Not really in my skill set or interest to add any more systems for the foreseeable future.
