### ISSUE TITLE
[bug report ] load the save will crash

### ISSUE THREAD

**Issue by nenge123** [Lit-Development/Ignited#25]
delta is no this bug

https://github.com/Lit-Development/Ignited/assets/16117315/53e5a4ba-93f8-4609-afec-6cfe659d11ba

**Comment by nenge123** [comment]
https://github.com/Lit-Development/Ignited/assets/16117315/0d92d46c-5217-4db9-b702-e44a2bcc09ee

**Comment by LitRitt** [comment]
What iOS version are you on? I'm not having any issues with save states on Genesis

**Comment by nenge123** [comment]
> What iOS version are you on? I'm not having any issues with save states on Genesis

my friend using you website version…… now  he will try github 1.4.4version
