### ISSUE TITLE
[BUG] Controllers Skin `+`

### ISSUE THREAD

**Issue by bachig26** [Lit-Development/Ignited#5]
I was trying to add multiple skins but having some issues around it, I've tried removing everything from `iPhone Storage -> Ignited` but still has the following issues.

- When I try adding 2nd or more custom skin, I can't add them in NDS.
- When I try to add skins to the N64, it displays the default one for every new custom skins.

I'm not sure but there might be some issue sqlite database in Delta Ignited relating the controller skins.

**Comment by LitRitt** [comment]
Can you provide some pictures or a video of exactly what's happening so I can better diagnose it?

**Comment by bachig26** [comment]
> Can you provide some pictures or a video of exactly what's happening so I can better diagnose it?

for example with N64 Skins:

The skins I used are from Skins4Delta: https://skins4delta.com/pages/n64

Army by Creator dumpty#5791: https://skins4delta.com/skins/n64/Army_N64.deltaskin
Bleu by Creator dumpty#5791: https://skins4delta.com/skins/n64/Bleu_N64.deltaskin

**_As you see in the clip, the custom skins tend to be added as the defaulted skin and sometimes the skins doesn't even load even after few restarts. I have tried the same skins with Delta where everything was fine._**

#### Clip

https://user-images.githubusercontent.com/96393348/229388435-8b05877f-309f-496e-a6af-843887df8e51.mp4

**Comment by bachig26** [comment]
@LitRitt I thought this might be an bug in my end, so I have removed the applied files from Ignited from `iPhone Storage > Ignited` and also few times completely removed the app itself and re-installed but this bug is persistent.

I also tried on my other iPhone and I can see this bug in there too.

**Comment by LitRitt** [comment]
I've tested those skins on all my devices and am seeing no issues. Closing until further reporting is done.

**Comment by LitRitt** [comment]
Upon further inspection of the skins, they contain the 'info.json' data for all layouts, but only provide images for iPhone edge to edge. These are malformed skins, not a problem with Ignited
