### ISSUE TITLE
[Feature Request] Controllers name customization

### ISSUE THREAD

**Issue by bachig26** [Lit-Development/Ignited#7]
This issue is to request an edit device name option for the controllers and host device to customize the name.

I really hoping for this feature to have the players name configured without changing the device name itself.

**Comment by LitRitt** [comment]
The fact that you can customize the name already in OS settings makes this a low priority, but I agree it is a worthwhile improvement once local multiplayer features mature more

**Comment by LitRitt** [comment]
Closing until it's a relevant idea
