### ISSUE TITLE
[Improvement] Game artwork autofetch

### ISSUE THREAD

**Issue by bachig26** [Lit-Development/Ignited#8]
as you may know that not every game titles display or set the artwork by default when the game is installed and we need to manually add them via files (photo or drive) or via the game database.

I would like see an autofetch artwork to the ignited where the games artwork is added to home page of ignited when installed. 
this function actually works well with Provenance, as I have tried every game that I had installed in Delta and now with Ignited where I can see the Provenance automatically fetches and sets the artwork to it but this function is not available in Delta and subsequently with Ignited.

I'm hoping to see this come to Ignited if it maybe implemented.

**Comment by LitRitt** [comment]
It is an available feature, but I believe some part of it is broken and the Delta dev is not aware. I will look into it when I can.
